#!/bin/bash

WEBROOT='/var/www/html'

# Remove sample config file
rm $WEBROOT/wp-config-sample.php

# Give direct upload/write permissions to WP users to install plugins and etc
echo $'\n\ndefine('FS_METHOD', 'direct');' >> $WEBROOT/wp-config.php

# Assign proper file permissions to wp-config file to prevent the wrong people from reading
chmod 440 $WEBROOT/wp-config.php
chown bobby:www-data $WEBROOT/wp-config.php
