#!/bin/bash

echo
echo "*******************************************************"
echo "This script will setup the wp site!"
echo "*******************************************************"
echo

read -p "Are you sure you want to continue? (yes/no) "
if [ "$REPLY" != "yes" ]; then
  exit 0
fi

echo
echo "Starting setup ..."

#################################################################
# Setup users, ssh, and aliases
#################################################################

# Create user
adduser bobby

# Give user sudo privileges
adduser bobby sudo

# Add SSH Key for User
su bobby -c "ssh-keygen"

mv /root/wp-files/authorized_keys /home/bobby/.ssh

# Add bash aliases, and source them
mv /root/wp-files/.bash_aliases /home/bobby/
su bobby -c "source /home/bobby/.bash_aliases"

mv /root/wp-files/sshd_config /etc/ssh/
service ssh restart
#################################################################
# Setup depedancies
#################################################################

# Get initial updates
apt-get update

# Install apache, php, and php apache dependancies
apt-get install -y apache2 php libapache2-mod-php

# Setup database on server
apt install -y mysql-server

# Install all extra php stuff
apt-get install -y php-mysql php-gd php-imagick

# Setup mailing
apt-get install -y postfix

# Setup zip/unzip to extract wp files
apt-get install -y zip unzip

service apache2 restart

################################################################
# Setup Database for WP Site
################################################################

echo
echo "************************************************"
echo "Setting up database for WP site!"
echo "************************************************"
echo

USERNAME="webmaster"

# Create new DB with the name of the user's input
read -p "What is the name of the new database?  "
DB_NAME="$REPLY"
mysql -u root -e "CREATE DATABASE $DB_NAME"
echo $'\nDatabase created!\n'

# Create new DB with the name of the user's input
read -p "What will the password be for webmaster user?  "
mysql -u root -e "CREATE USER '$USERNAME'@'localhost' identified by '$REPLY'"
mysql -u root -e "GRANT ALL PRIVILEGES ON $DB_NAME.* to '$USERNAME'@'localhost'"
mysql -u root -e "FLUSH PRIVILEGES"

################################################################
# Setup WP files, add proper permissions
################################################################
# Extract and move all files
mv /root/wp-files/wordpress-4.9.8.zip /var/www/html/
cd /var/www/html/
unzip wordpress-4.9.8.zip
mv wordpress/* . && rmdir wordpress
rm /var/www/html/wordpress-4.9.8.zip

# Assign proper owner/group and permissions
chown -R bobby:www-data /var/www/html
chmod -R 775 /var/www/html

# Remove initial apache index.html file
rm /var/www/html/index.html

#######################################
# Setup SSL Cetificates via Certbot
#######################################
# See: https://certbot.eff.org/
#apt-get update
#apt-get install -y software-properties-common
#add-apt-repository ppa:certbot/certbot
#apt-get update
#apt-get install -y python-certbot-apache
#sudo certbot --apache
